version: "3"

services:
  data-loader:
    image: quay.io/keboola/data-loader
    tty: true
    stdin_open: true
    volumes:
      - data:/data/
    environment:
      - KBC_CONFIG_ID
      - KBC_ROW_ID
      - KBC_CONFIG_VERSION
      - KBC_TOKEN
      - KBC_STORAGEAPI_URL
  sandbox:
    build: .
    image: keboola/docker-jupyter
    tty: true
    stdin_open: true
    volumes:
      - data:/data/
    ports:
      - "8888:8888"
    environment:
      - PASSWORD=test
      - TAGS=[]
      - PACKAGES=[]

volumes:
  data: